"use client"

// P11 E1 — Traceability tab on the MB Recipe detail page.
//
// ⛔ No new endpoint. Everything below comes from endpoints that already exist:
//   • the MB Head already loaded by the page (costProductId / costGeneratedAt /
//     costGeneratedBy),
//   • GET /api/v1/finance/mb-spins?mbhId=… (useMBSpins),
//   • GET /api/v1/finance/cost-results/{id}/history (useCostHistory).
//
// ⚠ OPEN GATE (recorded, not invented): the plan asks for `mbsCostProductId`
// per spin and for raw `cst_mb_cost` rows per period/cost type. Neither is
// reachable today:
//   • `MBSpin` (proto `finance.v1`) has NO cost-product field — see
//     src/types/generated/finance/v1/yarn_master.ts. The column is not on the
//     wire, so the spin table below shows the identity/cost-code fields that do
//     exist and states plainly that the per-spin cost product is unavailable.
//   • There is no `cst_mb_cost` read endpoint. The closest existing data is the
//     cost-result history of the MB cost product, which is what "Cost rows"
//     renders — labelled as what it actually is, not relabelled as cst_mb_cost.
// Both need a backend/proto change; this task is frontend-only, so nothing is
// fabricated here.

import Link from "next/link"

import { EmptyState } from "@/components/common/empty-state"
import { StatusBadge } from "@/components/common/status-badge"
import { UserName } from "@/components/common/user-name"
import { Badge } from "@/components/ui/badge"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import { calcTypeLabel, formatDate, formatNumeric } from "@/components/finance/cost-results/format"
import { useCostHistory } from "@/hooks/finance/use-cost-calc"
import { useMBSpins } from "@/hooks/finance/use-mb-spin"

import { isMbCostPossiblyStale, MbCostStaleWarning, resolveCostProductId } from "./mb-cost-tab"

interface Props {
  mbhId: string
  costProductId: number | undefined
  costGeneratedAt: string | undefined
  costGeneratedBy: string | undefined
  /** Parent MB Head workflow state — drives the stale-cost warning. See mb-cost-tab.tsx. */
  entryStatus: string | undefined
}

export function MbTraceabilityTab({
  mbhId,
  costProductId,
  costGeneratedAt,
  costGeneratedBy,
  entryStatus,
}: Props) {
  const productSysId = resolveCostProductId(costProductId)
  const { data: spinData, isLoading: spinsLoading } = useMBSpins({
    mbhId,
    page: 1,
    pageSize: 100,
  })
  const { data: history, isLoading: historyLoading } = useCostHistory(productSysId, {
    page: 1,
    pageSize: 50,
  })

  const spins = spinData?.data ?? []
  const costRows = history?.items ?? []

  const isStale = isMbCostPossiblyStale(productSysId !== undefined, entryStatus)

  return (
    <div className="space-y-6" data-testid="mb-traceability-tab">
      {isStale && <MbCostStaleWarning />}

      {/* ── MB cost product ── */}
      <Card>
        <CardHeader>
          <CardTitle className="text-sm font-semibold">MB cost product</CardTitle>
        </CardHeader>
        <CardContent className="space-y-3 text-sm">
          {productSysId === undefined ? (
            // D13: absent stays absent — no `?? 0`, no fake product link.
            <p className="text-sm text-muted-foreground" data-testid="trace-no-cost-product">
              No cost product has been generated for this recipe yet.
            </p>
          ) : (
            <div className="grid grid-cols-1 gap-3 sm:grid-cols-3">
              <TraceField label="Cost product">
                <Link
                  href={`/finance/product-master/${productSysId}`}
                  className="font-mono text-sm underline underline-offset-2"
                  data-testid="trace-cost-product-link"
                >
                  #{productSysId}
                </Link>
              </TraceField>
              <TraceField label="Cost generated at">
                <span className="text-sm">{formatDate(costGeneratedAt ?? null)}</span>
              </TraceField>
              <TraceField label="Cost generated by">
                {costGeneratedBy ? (
                  <UserName userId={costGeneratedBy} compact />
                ) : (
                  <span className="text-sm text-muted-foreground">—</span>
                )}
              </TraceField>
            </div>
          )}
        </CardContent>
      </Card>

      {/* ── Spins ── */}
      <Card>
        <CardHeader>
          <CardTitle className="text-sm font-semibold">
            Spins
            <span className="ml-2 text-xs font-normal text-muted-foreground">{spins.length}</span>
          </CardTitle>
          <p className="mt-1 text-xs text-muted-foreground">
            Per-spin cost product id is not exposed by the MB Spin API — the cost code below is the
            only linkage currently on the wire.
          </p>
        </CardHeader>
        <CardContent>
          {spinsLoading ? (
            <p className="py-2 text-sm text-muted-foreground">Loading…</p>
          ) : spins.length === 0 ? (
            <EmptyState title="No spins" description="This recipe has no MB Spin rows." />
          ) : (
            <div className="overflow-x-auto rounded-md border">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Name</TableHead>
                    <TableHead>MB costing</TableHead>
                    <TableHead>CC</TableHead>
                    <TableHead className="text-right">Rate MKT</TableHead>
                    <TableHead className="text-right">Run LDR %</TableHead>
                    <TableHead>Status</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {spins.map((s) => (
                    <TableRow key={s.mbsId}>
                      <TableCell className="text-sm">{s.mbsMgtName || "—"}</TableCell>
                      <TableCell className="font-mono text-xs">{s.mbsMbCosting || "—"}</TableCell>
                      <TableCell className="font-mono text-xs">{s.mbsCc || "—"}</TableCell>
                      <TableCell className="text-right font-mono text-sm tabular-nums">
                        {/* D13: undefined renders as an em dash via formatNumeric, never as 0. */}
                        {formatNumeric(s.mbsCostRateMkt ?? null)}
                      </TableCell>
                      <TableCell className="text-right font-mono text-sm tabular-nums">
                        {formatNumeric(s.mbsRunLdrPct ?? null)}
                      </TableCell>
                      <TableCell>
                        <Badge variant="outline" className="text-xs font-normal">
                          {s.mbsIsActive ? "Active" : "Inactive"}
                        </Badge>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          )}
        </CardContent>
      </Card>

      {/* ── Cost rows per period / cost type ── */}
      <Card>
        <CardHeader>
          <CardTitle className="text-sm font-semibold">
            Cost rows by period and cost type
            <span className="ml-2 text-xs font-normal text-muted-foreground">
              {costRows.length}
            </span>
          </CardTitle>
          <p className="mt-1 text-xs text-muted-foreground">
            Source: cost-result history of the MB cost product. Raw `cst_mb_cost` rows have no read
            endpoint yet.
          </p>
        </CardHeader>
        <CardContent>
          {productSysId === undefined ? (
            <p className="py-2 text-sm text-muted-foreground">No cost product to trace.</p>
          ) : historyLoading ? (
            <p className="py-2 text-sm text-muted-foreground">Loading…</p>
          ) : costRows.length === 0 ? (
            <EmptyState
              title="No cost rows"
              description="No calculated cost has been recorded for this cost product."
            />
          ) : (
            <div className="overflow-x-auto rounded-md border">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Period</TableHead>
                    <TableHead>Cost type</TableHead>
                    <TableHead>Version</TableHead>
                    <TableHead className="text-right">Cost per unit</TableHead>
                    <TableHead>Status</TableHead>
                    <TableHead>Calculated</TableHead>
                    <TableHead>By</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {costRows.map((r) => (
                    <TableRow key={r.costId}>
                      <TableCell className="font-mono text-sm">{r.period}</TableCell>
                      <TableCell className="text-sm">{calcTypeLabel(r.calculationType)}</TableCell>
                      <TableCell className="font-mono text-sm">v{r.version}</TableCell>
                      <TableCell className="text-right font-mono text-sm tabular-nums">
                        {formatNumeric(r.costPerUnit)}
                      </TableCell>
                      <TableCell>
                        <StatusBadge status={r.status} type="cost" size="sm" />
                      </TableCell>
                      <TableCell className="text-sm">{formatDate(r.calculatedAt)}</TableCell>
                      <TableCell className="text-sm">
                        {r.calculatedBy ? (
                          <UserName userId={r.calculatedBy} compact />
                        ) : (
                          <span className="text-muted-foreground">—</span>
                        )}
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  )
}

function TraceField({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="space-y-1">
      <div className="text-xs text-muted-foreground">{label}</div>
      <div>{children}</div>
    </div>
  )
}
